// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPZmB_kyE7RJaLS4dUCAO9c5WsWDJWqIM',
    appId: '1:128532727825:web:fbd309251fd2ecde3e89b0',
    messagingSenderId: '128532727825',
    projectId: 'zwap-v2',
    authDomain: 'zwap-v2.firebaseapp.com',
    storageBucket: 'zwap-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOJSBvsF6J1Q6GLWSzzJ1SF8yNcdk5Sgk',
    appId: '1:128532727825:android:79b764831969119e3e89b0',
    messagingSenderId: '128532727825',
    projectId: 'zwap-v2',
    storageBucket: 'zwap-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ikgTra-7NyDNvh5EhqTXWSAExhG2VQE',
    appId: '1:128532727825:ios:a9ebbb7c80d6cbcf3e89b0',
    messagingSenderId: '128532727825',
    projectId: 'zwap-v2',
    storageBucket: 'zwap-v2.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ikgTra-7NyDNvh5EhqTXWSAExhG2VQE',
    appId: '1:128532727825:ios:a9ebbb7c80d6cbcf3e89b0',
    messagingSenderId: '128532727825',
    projectId: 'zwap-v2',
    storageBucket: 'zwap-v2.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPZmB_kyE7RJaLS4dUCAO9c5WsWDJWqIM',
    appId: '1:128532727825:web:c51475ea06956b4f3e89b0',
    messagingSenderId: '128532727825',
    projectId: 'zwap-v2',
    authDomain: 'zwap-v2.firebaseapp.com',
    storageBucket: 'zwap-v2.firebasestorage.app',
  );
}
